services:
  crowdsec:
    image: ${CROWDSEC_IMAGE_TAG:-crowdsecurity/crowdsec:v1.7.7}
    container_name: crowdsec
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 8080:8080
      - 6060:6060
    volumes:
      - ./crowdsec/data:/var/lib/crowdsec/data
      - ./crowdsec/config:/etc/crowdsec
    healthcheck:
      test: ["CMD-SHELL", "cscli lapi status 2>&1 | grep -q 'on'"]
      start_period: 30s
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      crowdsec_net:
        ipv4_address: 172.21.0.10

  blocklist:
    image: ${CROWDSEC_BLOCKLIST_IMAGE_TAG:-crowdsecurity/blocklist-mirror:v0.0.6}
    container_name: blocklist
    restart: unless-stopped
    depends_on:
      crowdsec:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - 41412:41412
    volumes:
      - ./crowdsec-blocklist-mirror.yaml:/etc/crowdsec/bouncers/crowdsec-blocklist-mirror.yaml
    healthcheck:
      test: wget -qO- http://localhost:41412/metrics || exit 1
      start_period: 20s
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      crowdsec_net:
        ipv4_address: 172.21.0.20

networks:
  crowdsec_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/24
          gateway: 172.21.0.1